version: "3.7"
services:
  rabbit:
    container_name: ${PREFIX}-nameko-example-rabbitmq
    image: rabbitmq:3.7-management
    ports:              # Uncomment both lines if you want to debug
      - "15672:15672" 
      - "5672:5672"
    restart: unless-stopped
    healthcheck:
      # test: ["CMD-SHELL", "nc -z localhost 5672"]
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q status"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    container_name: ${PREFIX}-nameko-example-postgres
    image: postgres
    ports:            # Uncomment both lines if you want to debug
      - "5432:5432" # Exposing Postgres on different port for convenience
    environment:
        POSTGRES_DB: "orders"
        POSTGRES_PASSWORD: "password"
        POSTGRES_USER: "postgres"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: ${PREFIX}-nameko-example-redis
    image: redis
    ports:            # Uncomment both lines if you want to debug
      - "6379:6379" # Exposing Redis on different port for convenience
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5