"""init

Revision ID: 4b3f8eccfbf7
Revises: dd33cb03d01f
Create Date: 2021-10-01 16:57:20.301808

"""

# revision identifiers, used by Alembic.
revision = '4b3f8eccfbf7'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
