"""init

Revision ID: 5abea6e90b2f
Revises: 4b3f8eccfbf7
Create Date: 2021-10-01 16:58:42.836624

"""

# revision identifiers, used by Alembic.
revision = '5abea6e90b2f'
down_revision = '4b3f8eccfbf7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
