"""init

Revision ID: e5334279b836
Revises: 5abea6e90b2f
Create Date: 2021-10-01 17:35:50.982509

"""

# revision identifiers, used by Alembic.
revision = 'e5334279b836'
down_revision = '5abea6e90b2f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
